# sources/meta-poly-tc8/conf/machine/poly-tc8.conf

require conf/machine/imx8mm-lpddr4-evk.conf

MACHINEOVERRIDES =. "poly-tc8:"
UBOOT_DEVICETREE = "imx8mm-poly-lcc-proto.dtb"

# TODO:
# U-Boot overrides if needed
# Device tree implementation (poly-tc8.dts)
# We may need to change UART address and possilby serial console
