# sources/meta-poly-tc8/conf/machine/poly-tc8.conf

require conf/machine/imx8mm-lpddr4-evk.conf

# Change machine name
MACHINEOVERRIDES =. "poly-tc8:"

# Optional: Use eMMC as default flash target
UBOOT_CONFIG = "emmc"
UBOOT_CONFIG[emmc] = "imx8mm_evk_defconfig,emmc"

# Optional: Override device tree
KERNEL_DEVICETREE = "freescale/poly-tc8.dtb"

# Optional: set default console and bootargs
SERIAL_CONSOLES = "115200;ttymxc1"
